# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iPodcast' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~>2.6.3'
pod 'SDWebImage', '~> 3.8.2'
pod 'Masonry', '~> 1.0.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'IQKeyboardManager', '~> 4.0.6'
pod 'AVOSCloud', '~> 3.5.1'
pod 'UAProgressView', '~> 0.1.3'

# Pods for iPodcast

pod 'LeanCloudSocial'
pod 'UMengAnalytics'


end
